---
apiVersion: v2
name: strimzi-kafka-operator
version: 1.0.0
dependencies:
  - name: strimzi-kafka-operator
    version: 0.50.1
    repository: oci://quay.io/strimzi-helm
  - name: kafka-ui
    version: 1.6.0
    repository: https://ui.charts.kafbat.io/
