---
apiVersion: v2
name: crossplane
version: 1.0.0
dependencies:
  - name: crossplane
    version: 2.2.0
    repository: https://charts.crossplane.io/stable
  - name: komoplane
    version: 0.1.6
    repository: https://helm-charts.komodor.io
