---
apiVersion: v2
name: kube-prometheus-stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 75.18.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-blackbox-exporter
    version: 11.4.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-pushgateway
    version: 3.4.2
    repository: https://prometheus-community.github.io/helm-charts
